services:
  # showbuddy-landing:
  #   build: .
  #   volumes:
  #     - ./static:/app/static
  #   ports:
  #     - "5019:5019"

  showbuddy-app:
    build: .
    volumes:
      - ./static:/app/static
    ports:
      - "5019:5019"
    environment:
      - APP_MODE=app
      - ASSEMBLYAI_API_KEY
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - FIREFLIES_API_KEY=${FIREFLIES_API_KEY}
      - SPREADLY_API_KEY=${SPREADLY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION_ID=${OPENAI_ORGANIZATION_ID}
      - OPENAI_PROJECT_ID=${OPENAI_PROJECT_ID}
      - OPENWEBUI_API_KEY=${OPENWEBUI_API_KEY}
      - OPENWEBUI_URL=${OPENWEBUI_URL}
      - OPENWEBUI_LLAMA_MODEL=${OPENWEBUI_LLAMA_MODEL}
