services:
  showbuddy:
    build: .
    ports:
      - "5019:5019"
    env_file:
      - .env
    environment:
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - FIREFLIES_API_KEY=$FIREFLIES_API_KEY

