services:
  # showbuddy-landing:
  #   build: .
  #   volumes:
  #     - ./static:/app/static
  #   ports:
  #     - "5019:5019"

  showbuddy-app:
    build: .
    volumes:
      - ./static:/app/static
      - ./data:/data
    ports:
      - "5019:5019"
    environment:
      - APP_MODE=app
      - ASSEMBLYAI_API_KEY
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - FIREFLIES_API_KEY=${FIREFLIES_API_KEY}
      - SPREADLY_API_KEY

