name: wasp build

on:
  push:
    branches: [ "opensaas" ]
  
jobs:
  build:
    env:
      IMAGE: northamerica-northeast1-docker.pkg.dev/therumbler/xxx/showbuddy
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Run wasp build
      run: cd showbuddy/app && /home/brumble/.local/bin/wasp build

    - name: build docker image
      run: cd showbuddy/app && docker build ./.wasp/build -t $IMAGE-server:$GITHUB_SHA

    - name: push docker image
      run: docker push $IMAGE-server:$GITHUB_SHA